# Generated by Django 4.2.14 on 2024-08-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysummarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='summary_keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='summary_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
